export const AUDIT_EVENTS = {
  USER_GRANTED_CONSENT: "USER_GRANTED_CONSENT",
  USER_REVOKED_CONSENT: "USER_REVOKED_CONSENT",
  LISTING_IMPORTED: "LISTING_IMPORTED",
  MESSAGE_DRAFT_CREATED: "MESSAGE_DRAFT_CREATED",
  MESSAGE_SENT: "MESSAGE_SENT",
  INBOUND_MESSAGE_RECEIVED: "INBOUND_MESSAGE_RECEIVED",
  TOUR_CONFIRMED: "TOUR_CONFIRMED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  DOCUMENT_SHARED: "DOCUMENT_SHARED",
  APPLICATION_PACKET_SENT: "APPLICATION_PACKET_SENT",
  AGENT_TOOL_CALL_BLOCKED: "AGENT_TOOL_CALL_BLOCKED",
  ADMIN_VIEWED_DOCUMENT: "ADMIN_VIEWED_DOCUMENT",
  ADMIN_MODIFIED_LISTING: "ADMIN_MODIFIED_LISTING"
} as const;
