import type { RentcastRentalListing } from "./types";

export const rentcastFixtureListings: RentcastRentalListing[] = [
  {
    rentcastId: "rc-101",
    id: "rc-101",
    url: "https://provider.example/listings/rc-101",
    title: "1 bed near McCarren Park",
    address: "112 North 7th Street",
    unit: "4B",
    city: "Brooklyn",
    state: "NY",
    zip: "11249",
    price: 3650,
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 690,
    availableDate: "2026-07-01",
    amenities: ["laundry", "dishwasher", "elevator"],
    cats: true,
    dogs: false,
    applicationFee: 20,
    securityDeposit: 3650,
    contactName: "Mara",
    contactEmail: "leasing+mccarren@example.com",
    photos: ["/images/listing-kitchen.svg"],
    propertyType: "apartment"
  },
  {
    rentcastId: "rc-102",
    id: "rc-102",
    url: "https://provider.example/listings/rc-102",
    title: "Greenpoint walk-up with roof access",
    address: "71 Franklin Street",
    unit: "2R",
    city: "Brooklyn",
    state: "NY",
    zip: "11222",
    price: 3425,
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 640,
    availableDate: "2026-06-25",
    amenities: ["laundry", "outdoor space"],
    cats: true,
    dogs: true,
    applicationFee: 35,
    securityDeposit: 3425,
    contactName: "Leasing desk",
    contactEmail: "greenpoint-leasing@example.com",
    photos: ["/images/listing-living.svg"],
    propertyType: "apartment"
  },
  {
    rentcastId: "rc-103",
    id: "rc-103",
    url: "https://provider.example/listings/rc-103",
    title: "LIC high-floor one bedroom",
    address: "27-17 42nd Road",
    unit: "19C",
    city: "Queens",
    state: "NY",
    zip: "11101",
    price: 3895,
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 720,
    availableDate: "2026-07-03",
    amenities: ["doorman", "elevator", "gym", "laundry", "dishwasher"],
    cats: true,
    dogs: true,
    brokerFee: 3895,
    applicationFee: 20,
    securityDeposit: 3895,
    contactName: "Jon",
    contactEmail: "lic-towers@example.com",
    photos: ["/images/listing-bedroom.svg"],
    propertyType: "apartment"
  },
  {
    rentcastId: "rc-104",
    id: "rc-104",
    title: "Duplicate LIC high-floor one bedroom",
    address: "27-17 42nd Rd",
    unit: "19C",
    city: "Queens",
    state: "NY",
    zip: "11101",
    price: 3899,
    bedrooms: 1,
    bathrooms: 1,
    availableDate: "2026-07-03",
    amenities: ["doorman", "elevator", "gym"],
    cats: true,
    dogs: true,
    brokerFee: 3895,
    applicationFee: 20,
    securityDeposit: 3895,
    contactEmail: "lic-towers@example.com",
    photos: []
  }
];
